### ISSUE TITLE
Q: proxychains-ng PRNG

### ISSUE THREAD

**Issue by rofl0r** [audibleblink/doxycannon#26]
hello, do the problems you state about the randomchain seed also affect [proxychains-ng](https://github.com/rofl0r/proxychains-ng/) ?

btw note that "the original proxychains" repo you quote isn't original at all, it's a [fork by some random person](https://github.com/rofl0r/proxychains-ng/wiki/quality-of-haad's-fork,-or-%22reasons-for-the-split%22).

**Comment by audibleblink** [comment]
@rofl0r thanks for the heads up. def fooled me. 

unsure about the ng fork. i won't be able to check for a while, but I'll ping you again when life circumstances allow.

**Comment by rofl0r** [comment]
i suspect it will work as expected, because the original proxychains 3.1 code used a bogus method to get a random number, which we fixed. it should not be needed to reseed the rng all the time, a single srand() on startup should be sufficient.

**Comment by audibleblink** [comment]
hey @rofl0r 

Sorry it took me so long to look at this. I built from today's master of your fork. 

I used the following proxychain4.conf and seemed to be getting similar behavior to what I describe in the readme.

```
random_chain
quiet_mode
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
socks5 127.0.0.1 9000
socks5 127.0.0.1 9001
socks5 127.0.0.1 9002
socks5 127.0.0.1 9003
socks5 127.0.0.1 9004
socks5 127.0.0.1 9005
socks5 127.0.0.1 9006
socks5 127.0.0.1 9007
socks5 127.0.0.1 9008
socks5 127.0.0.1 9009
```

Inserting a sleep ensures a more random distribution between proxies:

```sh
$ while :; do curl ifconfig.io; sleep 1.1 ; done

185.112.146.85
185.220.100.254
104.244.75.80
185.220.100.254
198.144.120.234
107.189.10.119


$ while :; do curl ifconfig.io; done

185.191.124.151
185.191.124.151
185.220.100.254
185.220.100.254
185.220.100.254
185.112.146.85
185.112.146.85
107.189.10.119
```

**Comment by audibleblink** [comment]
This was the original patch on the haad fork 

```patch
From bd207014a20b41554207fc9ac9457e61ab570429 Mon Sep 17 00:00:00 2001
From: Alex Flores <domain@me.com>
Date: Fri, 30 Mar 2018 14:14:18 -0400
Subject: [PATCH] patch for better random proxy selection

---
 src/core.c | 17 +++++++++++++++--
 1 file changed, 15 insertions(+), 2 deletions(-)

diff --git a/src/core.c b/src/core.c
index c3a624d..b0e3f21 100644
--- a/src/core.c
+++ b/src/core.c
@@ -514,6 +514,19 @@ static int start_chain(int *fd, proxy_data * pd, char *begin_mark) {
 	return SOCKET_ERROR;
 }
 
+unsigned int get_rand_int(unsigned int range){
+    static FILE *fp;
+    unsigned int randval;
+    if (!fp) {
+        fp = fopen("/dev/urandom", "r");
+    }
+    if(fread(&randval, sizeof(randval), 1, fp)) {
+	return (randval % range);
+    } else {
+	srand((unsigned int)time(NULL));
+	return (rand() % range);
+    }
+}
 
 static proxy_data *select_proxy(select_type how, proxy_data * pd, unsigned int proxy_count, unsigned int *offset) {
 	unsigned int i = 0, k = 0;
@@ -522,10 +535,10 @@ static proxy_data *select_proxy(select_type how, proxy_data * pd, unsigned int p
 		return NULL;
 	switch (how) {
 		case RANDOMLY:
-			srand((unsigned int)time(NULL));
+
 			do {
 				k++;
-				i = 0 + (unsigned int) (proxy_count * 1.0 * rand() / (RAND_MAX + 1.0));
+				i = 0 + get_rand_int(proxy_count);
 			} while(pd[i].ps != PLAY_STATE && k < proxy_count * 100);
 			break;
 		case FIFOLY:
```

**Comment by audibleblink** [comment]
With my shitty C code applied to your fork

```sh
$ while :; do curl ifconfig.io; done
51.15.250.93
185.220.101.17
94.230.208.147
185.220.101.17
87.118.110.27
94.230.208.147
185.220.101.17
185.220.101.194
185.220.100.254
51.15.250.93
185.220.101.205
87.118.110.27
54.38.22.61
^C
```

**Comment by rofl0r** [comment]
oh, i finally get what this is really about:
basically we have a number of different processes that all use the same proxychains config, and when launching those in the same second they're all seeded with the same value and return same rand() result and therefore select the same proxy from the list. i guess we can fix that by using clock_gettime() to initialize srand(). i'll look into writing a fix tomorrow.
