### ISSUE TITLE
NordVpn

### ISSUE THREAD

**Issue by Bix3** [audibleblink/doxycannon#36]
Hello,

i tried to set it up with NordVpn but keep getting this error when doing --build
```
┌──(kali㉿kali)-[~/Desktop/doxy/doxycannon]
└─$ python3 doxycannon.py vpn --dir VPN --build
[+] Building image: audibleblink/doxycannon.
The command '/bin/sh -c apk --no-cache add openvpn dante-server supervisor &&   rm -rf /var/cache/' returned a non-zero code: 3
Traceback (most recent call last):
  File "/home/kali/Desktop/doxy/doxycannon/doxycannon.py", line 576, in <module>
    main(args)
  File "/home/kali/Desktop/doxy/doxycannon/doxycannon.py", line 552, in main
    handle_vpn(args)
  File "/home/kali/Desktop/doxy/doxycannon/doxycannon.py", line 537, in handle_vpn
    build(IMAGE)
  File "/home/kali/Desktop/doxy/doxycannon/doxycannon.py", line 69, in build
    doxy.images.build(path=path, tag=image, forcerm=True)
  File "/home/kali/.local/lib/python3.9/site-packages/docker/models/images.py", line 285, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c apk --no-cache add openvpn dante-server supervisor &&         rm -rf /var/cache/' returned a non-zero code: 3

```
i put the credentials in the NAME.txt file like described and changed the .ovpn files to auth-user-pass NAME.txt.
In Tor mode everything works as expected so my installation should be alright

i will be happy about any ideas which can help : )

**Comment by audibleblink** [comment]
Hey, thanks for the note.

I'm unable to reproduce.  Can you try to run the following and see if you get the same error?

```sh
$ docker run --rm -it alpine:latest
```

This will  drop you into the container's cmdline. once  in, run:

```
/ # apk --no-cache add openvpn dante-server supervisor
```

Does this complete successfully?

If so, what versions of OS and Docker are you running?

**Comment by Bix3** [comment]
Hello, after i made this issue i made a reinstall on a fresh vm and it works now, sadly i have deleted the other (older) vm and cant check which versions it was running.
