### ISSUE TITLE
Add the option of setting only Tor exit nodes (no VPNs)

### ISSUE THREAD

**Issue by BBerastegui** [audibleblink/doxycannon#9]
As proposed here: https://github.com/audibleblink/doxycannon/issues/6#issuecomment-407080627

It'll be awesome to have the option of allowing doxycannon to pop only docker tor containers that will be used as round-robin outgoing proxies for Haproxy.

`./doxycannon.py --only-tor --nodes 16`

That will popup 16 tor docker containers that will be used as outgoing proxies for Haproxy.

**Comment by audibleblink** [comment]
@BBerastegui hey

i've submitted PR #25 if you wanted to review and test. I tried with 3 nodes and it worked. Let me know if you run into any issues.
